services:
  db:
    image: postgres:16
    container_name: database
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - 5432:5432
    networks:
    - app-softdev

  backend:
    container_name: backend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - db
    links:
      - db
    networks:
      - app-softdev

    
    # volumes:
    #   - db_data:/var/lib/postgresql/data

# volumes:
#   db_data:

networks:
  app-softdev:
    driver: bridge
    external: true